# Basic settings
site_name: Playlab Learning Hub
site_url: https://wymankhuu.github.io/playlab-learning/
repo_url: https://github.com/wymankhuu/playlab-learning
docs_dir: docs
use_directory_urls: true

#Navigation
nav:
  - Home: index.md
  - About:
    - Contact Us: about/contactus.md
  - Features:
    - Overview: features/overview.md
    - Richer Starter Inputs: features/Richer Starter Inputs.md
    - Feature 2: features/feature2.md
    - Feature 3: features/feature3.md
  - Documentation:
    - FAQ: faq.md
    - Getting Started: getting-started.md

#Theme
theme:
  name: material
  font:
    text: DM sans
  icon:
    logo: ../assets/images/logo.png
    favicon: assets/favicon.ico
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: indigo
      
    # Emojis
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences


